# Generated by Django 3.1 on 2021-07-19 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='finished',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
