# Generated by Django 3.1 on 2021-07-20 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20210719_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('current', 'текущий'), ('processing', 'в обработке'), ('transporting', 'в доставке'), ('closed', 'завершенный'), ('dropped', 'отмененный')], default='current', max_length=50),
        ),
    ]
