# Generated by Django 3.1 on 2021-07-26 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20210726_1154'),
        ('orders', '0004_auto_20210726_1154'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='item',
            unique_together={('order', 'product')},
        ),
    ]
